### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MultiBoxPrior'

### ISSUE THREAD

**Issue by InesBeltaief** [oyxhust/ssd-text_detection#5]
trying to run " python train_synthtext.py " , it finish loading images and got the error of 
` anchors = mx.symbol.MultiBoxPrior(from_layer, sizes=size_str, ratios=ratio_str, \
AttributeError: 'module' object has no attribute 'MultiBoxPrior'
`
Any idea how to fix the error please ?

**Comment by oyxhust** [comment]
Seems you use the latest mxnet, there are some changes in SSD in the latest mxnet.

**Comment by oyxhust** [comment]
My mxnet version is 0.7.0 and warp-ctc is this version (https://github.com/baidu-research/warp-ctc/tree/5bfb46e83bcb338a09fbf875cb0b02bc39746b36). 
I put my mxnet and warpctc on baiduyun, you can download from this link (http://pan.baidu.com/s/1dEDgPiD).

**Comment by InesBeltaief** [comment]
heyy @oyxhust thanks for replying ! 
I use the version 0.10.1 of mxnet , do I have to install the 0.7 version to be able to run the SSD ?

**Comment by oyxhust** [comment]
@InesBeltaief yes, you should install the 0.7.0 version. Under this version, my SSD can run well. In the latest version, mxnet has move ssd to the "contrib" folder.

**Comment by harshalcse** [comment]
> My mxnet version is 0.7.0 and warp-ctc is this version (https://github.com/baidu-research/warp-ctc/tree/5bfb46e83bcb338a09fbf875cb0b02bc39746b36).
> I put my mxnet and warpctc on baiduyun, you can download from this link (http://pan.baidu.com/s/1dEDgPiD).

@oyxhust  I will unable to download mxnet please  share google drive link.
